name: Example Workflow

on:
  - pull_request

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: MrRobz/dt-hotfix-notify@main
        with:
          who-to-greet: 'Mona the Octocat'